// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIkkFdP4wzWPTRJuPSjMEVFFXlWgKVfLw',
    appId: '1:408171174612:web:35def5bcd8f953cf51b941',
    messagingSenderId: '408171174612',
    projectId: 'portfolio-3b2db',
    authDomain: 'portfolio-3b2db.firebaseapp.com',
    storageBucket: 'portfolio-3b2db.firebasestorage.app',
    measurementId: 'G-0D08XSGDFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt77RXszbqTAzUWLvkqrevUrKbjZR-ohI',
    appId: '1:408171174612:android:fbec77a27f185a3751b941',
    messagingSenderId: '408171174612',
    projectId: 'portfolio-3b2db',
    storageBucket: 'portfolio-3b2db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc2FiQiUYnIA5sIrfj5t00n7aWHSQGvAI',
    appId: '1:408171174612:ios:6b8648272b40d0b551b941',
    messagingSenderId: '408171174612',
    projectId: 'portfolio-3b2db',
    storageBucket: 'portfolio-3b2db.firebasestorage.app',
    iosBundleId: 'com.example.project3d',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc2FiQiUYnIA5sIrfj5t00n7aWHSQGvAI',
    appId: '1:408171174612:ios:6b8648272b40d0b551b941',
    messagingSenderId: '408171174612',
    projectId: 'portfolio-3b2db',
    storageBucket: 'portfolio-3b2db.firebasestorage.app',
    iosBundleId: 'com.example.project3d',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIkkFdP4wzWPTRJuPSjMEVFFXlWgKVfLw',
    appId: '1:408171174612:web:a4794d46a2f5324451b941',
    messagingSenderId: '408171174612',
    projectId: 'portfolio-3b2db',
    authDomain: 'portfolio-3b2db.firebaseapp.com',
    storageBucket: 'portfolio-3b2db.firebasestorage.app',
    measurementId: 'G-HNPYZGN4DH',
  );
}
